name: CI

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Validate commit
        run: |
          if ! git log -1 --pretty=%s | grep -E "^(feat|fix|chore|refactor|perf|docs)(\(.+\))?: .+"; then
            echo "Invalid commit"
            exit 1
          fi