name: Template Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1" # toda segunda-feira

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync template
        uses: repo-sync/github-sync@v2
        with:
          source_repo: minha-org/template-fivem
          source_branch: main
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

          create_pr: true

          pr_title: "chore(template): sync with template"
          pr_body: "Atualização automática do template base"
          pr_label: "template-sync"

          # evita sujeira
          exclude: |
            config/*
            *.local.lua
            .env
            .env.*
            .github/workflows/template-sync.yml